/* Board startup for the STM32H743VIT6 BSP. */

#include "board.h"

#include "gpio.h"
#include "usart.h"

static void bsp_mpu_config(void)
{
    MPU_Region_InitTypeDef mpu_config = {0};

    HAL_MPU_Disable();

    mpu_config.Enable = MPU_REGION_ENABLE;
    mpu_config.Number = MPU_REGION_NUMBER0;
    mpu_config.BaseAddress = 0x00000000U;
    mpu_config.Size = MPU_REGION_SIZE_4GB;
    mpu_config.SubRegionDisable = 0x87U;
    mpu_config.TypeExtField = MPU_TEX_LEVEL0;
    mpu_config.AccessPermission = MPU_REGION_NO_ACCESS;
    mpu_config.DisableExec = MPU_INSTRUCTION_ACCESS_DISABLE;
    mpu_config.IsShareable = MPU_ACCESS_SHAREABLE;
    mpu_config.IsCacheable = MPU_ACCESS_NOT_CACHEABLE;
    mpu_config.IsBufferable = MPU_ACCESS_NOT_BUFFERABLE;

    HAL_MPU_ConfigRegion(&mpu_config);
    HAL_MPU_Enable(MPU_PRIVILEGED_DEFAULT);
}

static void bsp_clock_config(void)
{
    RCC_OscInitTypeDef osc_config = {0};
    RCC_ClkInitTypeDef clock_config = {0};

    HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
    while (!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY))
    {
    }

    osc_config.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc_config.HSEState = RCC_HSE_ON;
    osc_config.PLL.PLLState = RCC_PLL_ON;
    osc_config.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    osc_config.PLL.PLLM = 4U;
    osc_config.PLL.PLLN = 240U;
    osc_config.PLL.PLLP = 2U;
    osc_config.PLL.PLLQ = 2U;
    osc_config.PLL.PLLR = 2U;
    osc_config.PLL.PLLRGE = RCC_PLL1VCIRANGE_2;
    osc_config.PLL.PLLVCOSEL = RCC_PLL1VCOWIDE;
    osc_config.PLL.PLLFRACN = 0U;
    if (HAL_RCC_OscConfig(&osc_config) != HAL_OK)
    {
        Error_Handler();
    }

    clock_config.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                             RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2 |
                             RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1;
    clock_config.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clock_config.SYSCLKDivider = RCC_SYSCLK_DIV1;
    clock_config.AHBCLKDivider = RCC_HCLK_DIV2;
    clock_config.APB3CLKDivider = RCC_APB3_DIV2;
    clock_config.APB1CLKDivider = RCC_APB1_DIV2;
    clock_config.APB2CLKDivider = RCC_APB2_DIV2;
    clock_config.APB4CLKDivider = RCC_APB4_DIV2;
    if (HAL_RCC_ClockConfig(&clock_config, FLASH_LATENCY_4) != HAL_OK)
    {
        Error_Handler();
    }
}

static void bsp_systick_init(void)
{
    HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK);
    HAL_SYSTICK_Config(SystemCoreClock / RT_TICK_PER_SECOND);
    HAL_NVIC_SetPriority(SysTick_IRQn, 0x0FU, 0U);
}

void bsp_systick_handler(void)
{
    rt_interrupt_enter();
    rt_tick_increase();
    rt_interrupt_leave();
}

#if defined(RT_USING_USER_MAIN) && defined(RT_USING_HEAP)
extern rt_uint8_t __heap_start__;
extern rt_uint8_t __heap_end__;

RT_WEAK void *rt_heap_begin_get(void)
{
    return &__heap_start__;
}

RT_WEAK void *rt_heap_end_get(void)
{
    return &__heap_end__;
}
#endif

void rt_hw_board_init(void)
{
    /* Preserve the initialization order generated by STM32CubeMX. */
    bsp_mpu_config();
    HAL_Init();
    bsp_clock_config();
    SystemCoreClockUpdate();
    bsp_systick_init();

    MX_GPIO_Init();
    MX_USART2_UART_Init();

#if defined(RT_USING_USER_MAIN) && defined(RT_USING_HEAP)
    rt_system_heap_init(rt_heap_begin_get(), rt_heap_end_get());
#endif

#ifdef RT_USING_COMPONENTS_INIT
    rt_components_board_init();
#endif
}

void Error_Handler(void)
{
    __disable_irq();
    while (1)
    {
    }
}
